### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.lang.AssertionError: Assert failed: Can't recur here

### ISSUE THREAD

**Issue by alvinlai** [ibdknox/live-cljs#2]
I'm on OS X 10.7.3, installed leiningen via homebrew.

Let me know if there's more information you need.

$ lein run
DOING:  goog.provide('coding.client.main');
goog.require('cljs.core');
goog.require('coding.client.util');
goog.require('waltz.state');
goog.require('coding.client.core');
goog.require('jayq.core');
goog.require('coding.client.editor');
goog.require('waltz.history');
goog.require('waltz.state');
goog.require('waltz.transition');
goog.require('monet.geometry');
goog.require('monet.canvas');
goog.require('clojure.string');
goog.require('clojure.browser.repl');

"Elapsed time: 46.338 msecs"
Exception in thread "main" java.lang.RuntimeException: java.lang.AssertionError: Assert failed: Can't recur here
frame
    at clojure.lang.Util.runtimeException(Util.java:165)
    at clojure.lang.Compiler.eval(Compiler.java:6476)
    at clojure.lang.Compiler.eval(Compiler.java:6455)
    at clojure.lang.Compiler.eval(Compiler.java:6431)
    at clojure.core$eval.invoke(core.clj:2795)
    at clojure.main$eval_opt.invoke(main.clj:296)
    at clojure.main$initialize.invoke(main.clj:315)
    at clojure.main$null_opt.invoke(main.clj:348)
    at clojure.main$main.doInvoke(main.clj:426)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:405)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:518)
    at clojure.main.main(main.java:37)
Caused by: java.lang.AssertionError: Assert failed: Can't recur here
frame
    at cljs.compiler$fn__2122.invoke(compiler.clj:766)
    at clojure.lang.MultiFn.invoke(MultiFn.java:177)
    at cljs.compiler$analyze_seq.invoke(compiler.clj:1040)
    at cljs.compiler$analyze.invoke(compiler.clj:1093)
    at cljs.compiler$analyze.invoke(compiler.clj:1086)
    at cljs.compiler$fn__2046.invoke(compiler.clj:606)
    at clojure.lang.MultiFn.invoke(MultiFn.java:177)
    at cljs.compiler$analyze_seq.invoke(compiler.clj:1040)
    at cljs.compiler$analyze.invoke(compiler.clj:1093)
    at cljs.compiler$analyze.invoke(compiler.clj:1086)
    at cljs.compiler$parse_invoke$fn__2261.invoke(compiler.clj:986)
    at clojure.core$map$fn__3811.invoke(core.clj:2432)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.PersistentVector.create(PersistentVector.java:50)
    at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:31)
    at clojure.core$vec.invoke(core.clj:345)
    at cljs.compiler$parse_invoke.invoke(compiler.clj:986)
    at cljs.compiler$analyze_seq.invoke(compiler.clj:1041)
    at cljs.compiler$analyze.invoke(compiler.clj:1093)
    at cljs.compiler$analyze.invoke(compiler.clj:1086)
    at cljs.compiler$fn__2046.invoke(compiler.clj:607)
    at clojure.lang.MultiFn.invoke(MultiFn.java:177)
    at cljs.compiler$analyze_seq.invoke(compiler.clj:1040)
    at cljs.compiler$analyze.invoke(compiler.clj:1093)
    at cljs.compiler$analyze.invoke(compiler.clj:1086)
    at cljs.compiler$parse_invoke$fn__2261.invoke(compiler.clj:986)
    at clojure.core$map$fn__3811.invoke(core.clj:2432)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.RT.seq(RT.java:466)
    at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:31)
    at clojure.core$vec.invoke(core.clj:345)
    at cljs.compiler$parse_invoke.invoke(compiler.clj:986)
    at cljs.compiler$analyze_seq.invoke(compiler.clj:1041)
    at cljs.compiler$analyze.invoke(compiler.clj:1093)
    at cljs.compiler$analyze.invoke(compiler.clj:1086)
    at cljs.compiler$parse_invoke$fn__2261.invoke(compiler.clj:986)
    at clojure.core$map$fn__3811.invoke(core.clj:2432)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.PersistentVector.create(PersistentVector.java:50)
    at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:31)
    at clojure.core$vec.invoke(core.clj:345)
    at cljs.compiler$parse_invoke.invoke(compiler.clj:986)
    at cljs.compiler$analyze_seq.invoke(compiler.clj:1041)
    at cljs.compiler$analyze.invoke(compiler.clj:1093)
    at cljs.compiler$analyze.invoke(compiler.clj:1086)
    at cljs.compiler$analyze_file.invoke(compiler.clj:1112)
    at coding.server$_main.doInvoke(server.clj:11)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.Var.invoke(Var.java:397)
    at user$eval30.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6465)
    ... 12 more

**Comment by cflewis** [comment]
I have the same issue, also with Mac OS X Lion and Homebrew's lein.

**Comment by ibdknox** [comment]
Look at the readme guys :p
